[package]
name = "dbmod_tui3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# JSON
serde_json = "1.0"

# PostgreSQL
postgres = "0.19.4"